version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/Zagreb"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/Zagreb"
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/Zagreb"
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope