/**
 * Custom semantic-release plugin for IPTVo that appends a "Contributors"
 * section (GitHub handles from authors + Co-authored-by trailers) to the
 * release notes generated by @semantic-release/release-notes-generator.
 *
 * Wired as a "generateNotes" plugin BEFORE the changelog/git plugins so the
 * annotated notes (with contributors) are what lands in CHANGELOG.md and the
 * release commit message.
 */
/**
 * Custom semantic-release plugins for IPTVo:
 *
 * 1. Contributors — appends a "Contributors" section (GitHub handles from
 *    authors + Co-authored-by trailers) to the release notes.
 *
 * 2. Pre-1.0 graduation — the first `feat:` on a pre-1.0 release bumps to
 *    1.0.0 (per project policy) instead of the default 0.x minor, matching
 *    the "first feature release graduates to 1.0.0" intent.
 */
/**
 * Enforces first-feature-graduates-to-1.0.0 for pre-1.0 projects.
 * Semantic-release composes all plugins' analyzeCommits and takes the highest
 * level; we return 'major' only when the project is still 0.x and the release
 * contains a feature (or a breaking change already escalates it).
 */
async function analyzeCommits(pluginConfig, context) {
  const previousVersion = (context.lastRelease && context.lastRelease.version) || '0.0.0';
  const isPreOne = /^0\./.test(previousVersion);
  if (!isPreOne) return null;

  const commits = context.commits || [];
  const hasFeat = commits.some(c => /^feat(\(.*\))?!?:/i.test(c.message || c.subject));
  const hasBreaking = commits.some(
    c => /^feat\(.*\)!:|^feat!:|^fix!:|^BREAKING CHANGE:/im.test(c.message || c.subject)
  );

  // Breaking already yields major via the analyzer; we only need to force it
  // for the first plain feat.
  if (hasBreaking) return 'major';
  if (hasFeat) return 'major';
  return null;
}

async function generateNotes(pluginConfig, context) {
  const { commits, logger } = context;
  // If pluginConfig.generator is an array `[name, options]` (semantic-release
  // plugin shorthand), unwrap to just the options. Otherwise pass as-is.
  let generatorOpts = pluginConfig.generator || {};
  if (Array.isArray(generatorOpts) && generatorOpts.length === 2) {
    generatorOpts = generatorOpts[1];
  }
  // The default release-notes-generator produces the base notes; call it here
  // (same options the project already configures so output stays consistent).
  const base = require('@semantic-release/release-notes-generator');
  let notes = '';
  try {
    notes = await base.generateNotes(generatorOpts, context);
  } catch (e) {
    logger.warn('release-notes-generator failed, continuing without base notes:', e.message);
  }

  // Aggregate contributors from authors + co-author trailers.
  const contributors = new Map();
  const addContributor = (name, email) => {
    if (!name || !email) return;
    let username = email.split('@')[0].replace(/\[bot\]$/, '');
    // Fall back to whichever side carries the GitHub handle.
    if (!username && name.startsWith('@')) username = name.slice(1);
    const key = `${name} <${email}>`;
    contributors.set(key, { name: name.replace(/[<>]/g, ''), username });
  };
  for (const commit of commits || []) {
    if (commit.author && commit.author.name && commit.author.email) {
      addContributor(commit.author.name, commit.author.email);
    }
    const body = commit.body || commit.subject || '';
    const re = /Co-authored-by:\s*([^<]+?)\s*<([^>]+)>/g;
    let m;
    while ((m = re.exec(body))) addContributor(m[1].trim(), m[2].trim());
  }

  const lines = [...contributors.values()].map(
    c => `- ${c.name} (@${c.username})`
  );

  if (lines.length === 0) return notes.trimEnd();
  const section = `${notes.trimEnd()}\n\n## 🤝 Contributors\n\n${lines.join('\n')}\n`;
  return section;
}

module.exports = { analyzeCommits, generateNotes };